def main():
    print("")
    print("                         TECNOLOGICO NACIONAL DE MEXICO")
    print("                        INSTITUTO TECNOLOGICO DE TIJUANA")
    print("")
    print("")
    print("                      DEPARTAMENTO DE SISTEMAS Y COMPUTACION")
    print("                        ING. EN SISTEMAS COMPUTACIONALES")
    print("                                SEMESTRE 2022-2")
    print("")
    print("                       LENGUAJES DE INTERFAZ (SCC-1014SC6C)")
    print("")
    print("")
    print("                                    ACTIVIDAD:")
    print("                          CREACION DE PORTADA EN PYTHON")
    print("")
    print("")
    print("                  Alumno: 19211641 FLORES SANDOVAL DIEGO EDUARDO")
    print("                         Maestro: RODRIGO CANEZ VALLE")
    print("")
    print("")
    print("                      Tijuana B.C. a 20 de septiembre de 2022")
